mimdb/carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.view,name='cart'),
    path('<int:id>/',views.remove_from_cart,name="remove_from_cart"),
    path('<slug:slug>/',views.add_to_cart,name="add_to_cart")
]

mimdb/mimdb/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('carts/',include('carts.urls')),
    
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

mimdb/products/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name="home"),
    path('s/',views.search,name="search"),
    path('products/',views.all,name='products'),
    path('products/<slug:slug>',views.single_product,name='single_product'),
    
]

mimdb/carts/models.py
from django.db import models
from products.models import Product,Variation
# Create your models here.

class CartItem(models.Model):
    cart =models.ForeignKey('Cart',null=True,blank=True,on_delete='CASCADE')
    #cart foreign key
    product = models.ForeignKey(Product,on_delete='CASCADE')
    variations = models.ManyToManyField(Variation,null=True,blank=True)
    quantity = models.IntegerField(default=1)
    line_total = models.DecimalField(default=10.99,max_digits=64,decimal_places=2)
    #line_total
    notes = models.TextField(null=True,blank=True)
    timestamp=models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)

    def __str__(self):
        try:
            return (str(self.cart.id)+'-'+str(self.product.title))
        except:
            return self.product.title

class Cart(models.Model):
    #items = models.ManyToManyField(CartItem,null=True,blank=True)
    #products = models.ManyToManyField(Product,null=True,blank=True)
    total = models.DecimalField(max_digits=64,decimal_places=2,default=0.00)
    timestamp=models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    active=models.BooleanField(default=True)

    def __str__(self):
        return "Cart id:"+str(self.id)

mimdb/products/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=True,blank=True)
    price = models.DecimalField(decimal_places=2,max_digits=50,default=69.99)
    sale_price = models.DecimalField(decimal_places=2,max_digits=50,null=True,blank=True)
    
    slug = models.SlugField(unique=True)
    timestamp=models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    active=models.BooleanField(default=True)

    def __str__(self):
        return self.title
    
    class Meta:
        unique_together = ('title','slug')

    def get_absolute_url(self):
        return reverse("single_product",kwargs={"slug":self.slug})

class ProductImage(models.Model):
    product = models.ForeignKey(Product,on_delete='CASCADE')
    image=models.ImageField(upload_to='products/images/')
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active=models.BooleanField(default=True)

    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    def __str__(self):
        return self.product.title

class VariationManager(models.Manager):
    def all(self):
        return super(VariationManager,self).filter(active=True)
    def sizes(self):
        return self.all().filter(category='size')
    def colors(self):
        return self.all().filter(category='color')
    def packages(self):
        return self.all().filter(category='package')

VAR_CATEGORIES = (
    ('size','size'),
    ('color','color'),
    ('package','package'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product,on_delete='CASCADE')
    category=models.CharField(max_length=120,choices=VAR_CATEGORIES,default='size')
    title = models.CharField(max_length=120)
    image = models.ForeignKey(ProductImage,null=True,blank=True,on_delete='CASCADE')
    price = models.DecimalField(null=True,blank =True,decimal_places=2,max_digits=50)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    active=models.BooleanField(default=True)

    objects = VariationManager()
    def __str__(self):
        return self.title

mimdb/carts/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.urls import reverse

from .models import Cart,CartItem
from products.models import Product,Variation

def view(request):
    try:
        the_id = request.session['cart_id']
    except:
        the_id=None
    if the_id:
        cart = Cart.objects.get(id=the_id)
        #every time we view the cart it will actually update for us
        sum=0.00
        for item in cart.cartitem_set.all():
            line_total = float(item.product.price)*item.quantity
            sum+=line_total
        request.session['items_total']=cart.cartitem_set.count()
        cart.total=sum
        cart.save()
        context = {"cart":cart}
    else:
        empty_message="Your cart is empty,Please Keep Shopping"
        context = {"empty":True,"empty_message":empty_message}

    template = "carts/view.html"
    return render(request,template,context)

def remove_from_cart(request,id):
    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        return HttpResponseRedirect(reverse("cart"))    
 
    cartitem = CartItem.objects.get(id=id)
    #cartitem.delete()
    cartitem.cart = None
    cartitem.save()
    #send  "Success message"
    return HttpResponseRedirect(reverse("cart"))

def add_to_cart(request,slug):
    request.session.set_expiry(120000)
    #cart session code
    try:
        the_id = request.session['cart_id']
    except:
        new_cart = Cart()
        new_cart.save()
        request.session['cart_id']=new_cart.id
        the_id = new_cart.id
    
    cart = Cart.objects.get(id=the_id)

    try:    
        product = Product.objects.get(slug=slug)
    except Product.DoesNotExist:
        pass
    except:
        pass

    product_var=[]  #product variation
    if request.method == "POST":
        qty=request.POST['qty']
        
        for item in request.POST:
            key = item
            val = request.POST[key]
            try:
                v=Variation.objects.get(product=product,category__iexact=key,title__iexact=val)
                product_var.append(v)
            except:
                pass

        # ("model object","true/false")
        cart_item= CartItem.objects.create(cart=cart,product=product)
        if len(product_var)>0:
            cart_item.variations.add(*product_var)
        cart_item.quantity = qty
        cart_item.save()
        #Success message 
        return HttpResponseRedirect(reverse("cart"))
    #error message
    return HttpResponseRedirect(reverse("cart"))

mimdb/products/views.py
from django.shortcuts import render
from .models import Product
# Create your views here.
def home(request):
    products = Product.objects.all()
    template='products/home.html'
    context={'products':products}
    return render(request,template,context)

def all(request):
    template = 'products/all.html'
    context = {'products':Product.objects.all()}
    return render(request,template,context)


def single_product(request,slug):
    try:
        product = Product.objects.get(slug=slug)
        products=Product.objects.all()
        template = 'products/single.html'
        context = {'product':product}
        return render(request,template,context)
    except:
        pass
def search(request):
    try:
        q=request.GET.get('q')
    except:
        q=None
    if q:
        products = Product.objects.filter(title__icontains=q)
        template='products/results.html'
        context={'query':q,'products':products}
    else:
        template='products/home.html'
        context={}
            
    return render(request,template,context)

mimdb/products/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ABHIZON</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/estyle.css' %}"/>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
  </head>

  <body>
    {% include 'navbar.html' %}
    
    {% block content %}
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

mimdb/products/templates/carts/view.html
{% extends "base.html" %}
{%  block content  %}
{% if empty %}
    <h1 style='text-align:center'>{{empty_message}}</h1>
{% else %}
    <div class="col-sm-8 offset-sm-2">
        <table class="table">
            <thead>
                <th>Item</th>
                <th>Price</th>
                <th>Qty</th>
            </thead>
            <tfoot>
                <tr>
                    <td>Total: {{ cart.total }}</td>
                </tr>
            </tfoot>
            {% for item in cart.cartitem_set.all %}
                <tr>
                    <td>{{item.product}}{% if item.variations.all %}
                            <ul>{% for subitem in item.variations.all %}
                                 <li>{{ subitem.category|capfirst}} : {{subitem.title|capfirst}}</li> 
                                {% endfor %}</ul>
                        {% endif %} </td>
                    <td>{{item.product.price}}</td>
                    <td>{{item.quantity}}</td>
                    <td><a href='{% url "remove_from_cart" item.id %}'>Remove</a></td>
                </tr>
            {% endfor%}
        </table>
    </div>
    {% endif %}
{% endblock %}

mimdb/products/templates/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="{% url 'home' %}">AbhiZon</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" 
    data-target="#navbarCollapse" aria-controls="navbarCollapse" 
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">
          Home </a>
      </li>
      
    </ul>
    <form class="form-inline mt-2 mt-md-0" role="search" action='/s/'>
      <input class="form-control mr-sm-2" type="text" 
          placeholder="Search" name='q' aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" 
          type="submit">Search</button>
    </form>
    <ul class="nav navbar-nav navbar-right">

      <li class="nav-item active">
          <a class="nav-link" href="{% url 'products' %}">Products </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cart' %}">Cart 
          <span class="badge badge-light">
            {% if not request.session.items_total %} 0 
            {% else %} {{request.session.items_total}} 
            {% endif %}
        </span></a>
      </li>
     
    </ul>
  </div>
  </nav>

mimdb/products/templates/products/all.html
{% extends 'base.html' %}

{% block content %}
    <div class='container'>
        {% for prod in products %}
            <h1>{{prod.id}}. {{prod.title}} ({{prod.price}}) <br></h1>
        {% endfor %}
    </div>
{% endblock %}

mimdb/products/templates/products/home.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}
<div class="container">
  <div class="row">
    {% for prod in products %}
    <div class="col-sm-4">
      <div class="img-thumbnail">
      {% if prod.productimage_set.all %}
        {% for item in prod.productimage_set.all %}

          {% if item.featured %}
            <img src="{{item.image.url}}" class='img-fluid'>
          {% endif %}

          <br/>
        {% endfor %}
      {% else %}
        <img src="{% static 'img/placeholder.png' %}" class='img-fluid'><br/>
      {% endif %}

      <div class="caption">
        <h3> {{prod.id}}. <a href="{{ prod.get_absolute_url }}">{{prod.title}}</a>({{prod.price}})</h3>
        <p>{{prod.description}}</p>
        <p><a href="{{ prod.get_absolute_url }}"><button type="button" class= "btn btn-info">View</button></a></p>
      </div>
      </div>
      </div>
      {% cycle "" "" "</div><br/><hr/><div class='row'>"%}
      
    {% endfor %}

  </div>
</div>
{% endblock %}

mimdb/products/templates/products/results.html
{% extends 'base.html' %}

{% block content %}
    
    <h1>Searched for:{{query}}</h1>
    {% for prod in products %}
        {% for item in prod.productimage_set.all %}
            <img src='{{item.image.url}}' class="img-fluid">
        {% endfor %}
    {% endfor %}
{% endblock %}

mimdb/products/templates/products/single.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
      <div class="row">
        <div class='col-sm-4'>
        {% for item in product.productimage_set.all %}  <!--product images for loop-->
          {% if item.featured %}
            <div class="col-md-12">
              <img src="{{item.image.url}}" class='img-responsive img-fluid'>
            </div><hr/>
          {% endif %}
        {% endfor %}
        <div class="row">
        {% for item in product.productimage_set.all %}
          {% if not item.featured %}
            
              <div class="col-md-4">
              <img src="{{item.image.url}}" class='img-fluid img-thumbnail'>
            </div>
          {% endif %}
        {% endfor %}
        </div>
            
      </div>
      <div class="col-sm-8">
        <div class='col-sm-12'>
            <h1>{{product.title}}</h1>
            <!-- <h1><a href="{% url 'add_to_cart' product.slug %}" class="btn btn-primary float-right">Add To Cart</a></h1>
            -->
          </div>
        <div class='col-sm-12'>
          <form class='form' method='POST' action='{% url "add_to_cart" product.slug %}'>
            {% csrf_token %}
            <div class='col-sm-3 float-left'>
             <input class='form-control' name='qty' type='number' value='1' />
            </div>
            {%  if product.variation_set.all %}
            
            <div class='col-sm-3 float-left'>
            {% if product.variation_set.sizes %}
              <select class='form-control' name='size'>
              {% for item in product.variation_set.sizes %}
                <option value='{{item.title|lower}}'>{{item.title|capfirst}}</option>
              {% endfor %}
              </select>
            {% endif %}
            </div>
            <div class='col-sm-3 float-left'>
            {% if product.variation_set.colors %}
              <select class='form-control' name='color'>
              {% for item in product.variation_set.colors %}
                <option value='{{item.title|lower}}'>{{item.title|capfirst}}</option>
              {% endfor %}
              </select>
            {% endif %}
          </div>
            <div class='col-sm-3 float-left'>
            {% if product.variation_set.packages %}
              <select class='form-control' name='package'>
              {% for item in product.variation_set.packages %}
                <option value='{{item.title|lower}}'>{{item.title|capfirst}}</option>
              {% endfor %}
              </select>
            {% endif %}
          </div>
            {% endif %}
            <input class="btn btn-primary" type='submit' value='Add to cart' />
          </form>
        </div>
      <div class='col-sm-12'>
      <hr/>
        Price : {{product.price}}<br>
        Shipping free with $25+ purchase<hr/>
      </div>
      <div class='col-sm-12'>
        <p id="feat">{{product.description|linebreaks}}</p>
      </div>
    </div>
</div>  
{% endblock %}